server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5431/fraud
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

service:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true